var hierarchy =
[
    [ "com.example.restapi.model.CheckIn", "classcom_1_1example_1_1restapi_1_1model_1_1CheckIn.html", null ],
    [ "com.example.restapi.controller.CheckInController", "classcom_1_1example_1_1restapi_1_1controller_1_1CheckInController.html", null ],
    [ "com.example.restapi.unitarios.controller.CheckInControllerTest", "classcom_1_1example_1_1restapi_1_1unitarios_1_1controller_1_1CheckInControllerTest.html", null ],
    [ "com.example.restapi.service.CheckInService", "classcom_1_1example_1_1restapi_1_1service_1_1CheckInService.html", null ],
    [ "com.example.restapi.unitarios.service.CheckInServiceTest", "classcom_1_1example_1_1restapi_1_1unitarios_1_1service_1_1CheckInServiceTest.html", null ],
    [ "com.example.restapi.unitarios.model.CheckInTest", "classcom_1_1example_1_1restapi_1_1unitarios_1_1model_1_1CheckInTest.html", null ],
    [ "com.example.restapi.controller.CheckOutController", "classcom_1_1example_1_1restapi_1_1controller_1_1CheckOutController.html", null ],
    [ "com.example.restapi.unitarios.controller.CheckOutControllerTest", "classcom_1_1example_1_1restapi_1_1unitarios_1_1controller_1_1CheckOutControllerTest.html", null ],
    [ "com.example.restapi.service.CheckOutService", "classcom_1_1example_1_1restapi_1_1service_1_1CheckOutService.html", null ],
    [ "com.example.restapi.unitarios.service.CheckOutServiceTest", "classcom_1_1example_1_1restapi_1_1unitarios_1_1service_1_1CheckOutServiceTest.html", null ],
    [ "com.example.restapi.model.Cliente", "classcom_1_1example_1_1restapi_1_1model_1_1Cliente.html", null ],
    [ "com.example.restapi.controller.ClienteController", "classcom_1_1example_1_1restapi_1_1controller_1_1ClienteController.html", null ],
    [ "com.example.restapi.unitarios.controller.ClienteControllerTest", "classcom_1_1example_1_1restapi_1_1unitarios_1_1controller_1_1ClienteControllerTest.html", null ],
    [ "com.example.restapi.integracion.repository.ClienteRepositoryIT", "classcom_1_1example_1_1restapi_1_1integracion_1_1repository_1_1ClienteRepositoryIT.html", null ],
    [ "com.example.restapi.service.ClienteService", "classcom_1_1example_1_1restapi_1_1service_1_1ClienteService.html", null ],
    [ "com.example.restapi.unitarios.service.ClienteServiceTest", "classcom_1_1example_1_1restapi_1_1unitarios_1_1service_1_1ClienteServiceTest.html", null ],
    [ "com.example.restapi.unitarios.model.ClienteTest", "classcom_1_1example_1_1restapi_1_1unitarios_1_1model_1_1ClienteTest.html", null ],
    [ "com.example.restapi.DataLoader", "classcom_1_1example_1_1restapi_1_1DataLoader.html", null ],
    [ "com.example.restapi.model.Habitacion", "classcom_1_1example_1_1restapi_1_1model_1_1Habitacion.html", null ],
    [ "com.example.restapi.controller.HabitacionController", "classcom_1_1example_1_1restapi_1_1controller_1_1HabitacionController.html", null ],
    [ "com.example.restapi.integracion.controller.HabitacionControllerIT", "classcom_1_1example_1_1restapi_1_1integracion_1_1controller_1_1HabitacionControllerIT.html", null ],
    [ "com.example.restapi.unitarios.controller.HabitacionControllerTest", "classcom_1_1example_1_1restapi_1_1unitarios_1_1controller_1_1HabitacionControllerTest.html", null ],
    [ "com.example.restapi.service.HabitacionService", "classcom_1_1example_1_1restapi_1_1service_1_1HabitacionService.html", null ],
    [ "com.example.restapi.unitarios.model.HabitacionTest", "classcom_1_1example_1_1restapi_1_1unitarios_1_1model_1_1HabitacionTest.html", null ],
    [ "JpaRepository", null, [
      [ "com.example.restapi.repository.CheckInRepository", "interfacecom_1_1example_1_1restapi_1_1repository_1_1CheckInRepository.html", null ],
      [ "com.example.restapi.repository.ClienteRepository", "interfacecom_1_1example_1_1restapi_1_1repository_1_1ClienteRepository.html", null ],
      [ "com.example.restapi.repository.HabitacionRepository", "interfacecom_1_1example_1_1restapi_1_1repository_1_1HabitacionRepository.html", null ],
      [ "com.example.restapi.repository.ProblemaRepository", "interfacecom_1_1example_1_1restapi_1_1repository_1_1ProblemaRepository.html", null ],
      [ "com.example.restapi.repository.ReservaRepository", "interfacecom_1_1example_1_1restapi_1_1repository_1_1ReservaRepository.html", null ]
    ] ],
    [ "com.example.restapi.model.Problema", "classcom_1_1example_1_1restapi_1_1model_1_1Problema.html", null ],
    [ "com.example.restapi.controller.ProblemaController", "classcom_1_1example_1_1restapi_1_1controller_1_1ProblemaController.html", null ],
    [ "com.example.restapi.service.ProblemaService", "classcom_1_1example_1_1restapi_1_1service_1_1ProblemaService.html", null ],
    [ "com.example.restapi.model.Reserva", "classcom_1_1example_1_1restapi_1_1model_1_1Reserva.html", null ],
    [ "com.example.restapi.controller.ReservaController", "classcom_1_1example_1_1restapi_1_1controller_1_1ReservaController.html", null ],
    [ "com.example.restapi.unitarios.controller.ReservaControllerTest", "classcom_1_1example_1_1restapi_1_1unitarios_1_1controller_1_1ReservaControllerTest.html", null ],
    [ "com.example.restapi.integracion.repository.ReservaRepositoryIT", "classcom_1_1example_1_1restapi_1_1integracion_1_1repository_1_1ReservaRepositoryIT.html", null ],
    [ "com.example.restapi.service.ReservaService", "classcom_1_1example_1_1restapi_1_1service_1_1ReservaService.html", null ],
    [ "com.example.restapi.unitarios.service.ReservaServiceTest", "classcom_1_1example_1_1restapi_1_1unitarios_1_1service_1_1ReservaServiceTest.html", null ],
    [ "com.example.restapi.unitarios.model.ReservaTest", "classcom_1_1example_1_1restapi_1_1unitarios_1_1model_1_1ReservaTest.html", null ],
    [ "com.example.restapi.RestApiApplication", "classcom_1_1example_1_1restapi_1_1RestApiApplication.html", null ]
];