var namespacecom_1_1example_1_1restapi_1_1integracion_1_1repository =
[
    [ "ClienteRepositoryIT", "classcom_1_1example_1_1restapi_1_1integracion_1_1repository_1_1_cliente_repository_i_t.html", "classcom_1_1example_1_1restapi_1_1integracion_1_1repository_1_1_cliente_repository_i_t" ],
    [ "ReservaRepositoryIT", "classcom_1_1example_1_1restapi_1_1integracion_1_1repository_1_1_reserva_repository_i_t.html", "classcom_1_1example_1_1restapi_1_1integracion_1_1repository_1_1_reserva_repository_i_t" ]
];